### ISSUE TITLE
Update Composer

### ISSUE THREAD

**Issue by remoteclient** [coopTilleuls/CoopTilleulsAclSonataAdminExtensionBundle#18]
Please update the composer.json to support Sonata Admin 3.x

Thanks in advance.

**Comment by sroze** [comment]
Can you do it and send us a pull-request?

**Comment by paulmonty** [comment]
+
I would love to help with this but don't know how so waiting for more experienced guys to update composer.

**Comment by meyerbaptiste** [comment]
Our extension now supports Sonata Admin 3.x. Please take a look a this merged PR: #19.

**Comment by paulmonty** [comment]
How to download it through composer?
When I got with require it doesn't work.
