### ISSUE TITLE
"Sonata\AdminBundle\Admin\AdminExtension", extended by  "CoopTilleuls\Bundle\AclSonataAdminExtensionBundle\Admin\AclAdminExtension", deprecated in "sonata-project/admin-bundle": "3.x-dev" with Symfony 3.3.10

### ISSUE THREAD

**Issue by 0l1v3r5** [coopTilleuls/CoopTilleulsAclSonataAdminExtensionBundle#27]
The "CoopTilleuls\Bundle\AclSonataAdminExtensionBundle\Admin\AclAdminExtension" class extends "Sonata\AdminBundle\Admin\AdminExtension" that is deprecated since version 3.1, to be removed in 4.0. Use Sonata\AdminBundle\AbstractAdminExtension instead

![capture d ecran de 2017-12-26 15-08-25](https://user-images.githubusercontent.com/29924640/34360167-6d462c66-ea5e-11e7-92d8-5ad5b7fa180c.png)

**Comment by dunglas** [comment]
It needs an update. Would you mind opening a Pull Request?

As we want to support both 3.x and 4.x, you'll probably need to conditionally define the inherited class like this:

```php

if class_exist(/* a class only in 4.0 */) {
    abstract class InternalAbstractClass extends AbstractAdminExtension {}
} else {
    abstract class InternalAbstractClass extends AdminExtension {}
}

class AclAdminExtension extends InternalAbstractClass
{
  // ...
}
```

**Comment by 0l1v3r5** [comment]
Ok I am working on it

**Comment by dunglas** [comment]
Thanks!

**Comment by 0l1v3r5** [comment]
You're welcome.
